#! /usr/bin/env python3
"""crmgr.

    CRM database manager.

Usage:
    crmgr find <pattern> [options]
    crmgr add country <iso> <name> [--original-name=<name>]
    crmgr add state <country> <iso> <name>
    crmgr add address <street> <house_number> <zip_code> <city> \
[--state-id=<state>]
    crmgr add po-box <po_box> <city> [--state-id=<state>]
    crmgr add company <name> [--address-id=<address>] \
[--annotation=<annotation>]
    crmgr add department <name> [--type=<type>]
    crmgr add employee <company> <department> <surname> <phone> \
[--fist-name=<name>] [--cellphone=<cellphone>] [--email=<email>] \
[--alt-phone=<phone>] [--fax=<fax>] [--address-id=<address>]
    crmgr add customer <company> [--annotation=<annotation>]

Options:
    --customer, -C          Find customers.
    --company, -O           Find companies.
    --department, -D        Find departments.
    --employee, -E          Find employees.
    --address, -A           Find addresses.
    --country, -N           Find countries.
    --state, -S             Find states.
    --name, -n              Prints name of search target instead of ID.
    --state-id=<state>      Specifies the state ID to set.
    --address-id=<address>  Specifies the address ID to set.
    --help , -h             Prints this page.
"""
from sys import stdout, stderr, exit as exit_

from homeinfo.crm import Country, State, Address, Company, Department, \
    Employee, Customer


def find(options):
    """Find model matching pattern."""

    pattern = options['<pattern>']

    if options['--customer']:
        yield from Customer.find(pattern)

    if options['--company']:
        yield from Company.find(pattern)

    if options['--department']:
        yield from Department.find(pattern)

    if options['--employee']:
        yield from Employee.find(pattern)

    if options['--address']:
        yield from Address.find(pattern)

    if options['--country']:
        yield from Country.find(pattern)

    if options['--state']:
        yield from State.find(pattern)


def print_model(model, print_name):
    """Prints the respective model instance."""

    if isinstance(model, Customer):
        ident = '/'.join(customer.cid for customer in model.reselling_chain)
        name = model.name
    else:
        ident = model.id
        name = str(model)

    print(ident, file=stderr if print_name else stdout, flush=True)
    print(name, file=stdout if print_name else stderr, flush=True)


def main(options):
    """Runs the crmgr."""

    if options['find']:
        for model in find(options):
            print_model(model, options['--name'])
    else:
        print('Operation currently not implemented.', file=stderr, flush=True)
        exit_(3)


if __name__ == '__main__':
    from docopt import docopt
    main(docopt(__doc__))
